ALTER TABLE users
ADD COLUMN full_name VARCHAR(50),
ADD COLUMN email VARCHAR(255) UNIQUE,
ADD COLUMN bio VARCHAR(300),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;